import{A as _,a as p,S as b}from"./assets/vendor-BnKFBj3L.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))r(n);new MutationObserver(n=>{for(const o of n)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(n){const o={};return n.integrity&&(o.integrity=n.integrity),n.referrerPolicy&&(o.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?o.credentials="include":n.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(n){if(n.ep)return;n.ep=!0;const o=s(n);fetch(n.href,o)}})();(()=>{const e={openModalBtn:document.querySelector("[data-menu-open]"),closeModalBth:document.querySelector("[data-menu-close]"),modalBtns:document.querySelectorAll(".modal-nav-link"),modal:document.querySelector("[data-modal]")};e.openModalBtn.addEventListener("click",t),e.closeModalBth.addEventListener("click",t),e.modalBtns.forEach(s=>{s.addEventListener("click",t)});function t(){e.modal.classList.toggle("is-open")}})();const a={CSS_SELECTOR:{WRAP_CLASS:".wrap",TECH_SKILLS_UPPER_ID:"#tech-skills-upper",TECH_SKILLS_LOWER_ID:"#tech-skills-lower"},CSS_CLASS:{ITEM:"item",UPPER_DOTS:"upper-dots",LOWER_DOTS:"lower-dots",ITEM_UPPER:"item-upper",ITEM_LOWER:"item-lower"},SEPARATOR_SVG_LOC:"./img/icons.svg#icon-dot",PLACE:{UPPER:"upper",LOWER:"lower"},POSITION:{BEFORE_END:"beforeend",AFTER_BEGIN:"afterbegin",AFTER_END:"afterend",BEFORE_BEGIN:"beforebegin"}},E=[{name:"HTML/CSS",link:"https://www.edu.goit.global/uk/learn/24554709/17039071/17039078/training"},{name:"JavaScript",link:"https://developer.mozilla.org/en-US/docs/Web/JavaScript"},{name:"React",link:"https://react.dev/"},{name:"Node.js",link:"https://nodejs.dev/"},{name:"React Native",link:"https://reactnative.dev/"},{name:"Typescript",link:"https://www.typescriptlang.org/"}],L=document.querySelector(a.CSS_SELECTOR.WRAP_CLASS),l=L.querySelector(a.CSS_SELECTOR.TECH_SKILLS_UPPER_ID),C=L.querySelector(a.CSS_SELECTOR.TECH_SKILLS_LOWER_ID),S=(e,t=a.PLACE.UPPER)=>e.map(s=>`<svg class=${t===a.PLACE.UPPER?a.CSS_CLASS.UPPER_DOTS:a.CSS_CLASS.LOWER_DOTS} width="8" height="8">
            <use href=${a.SEPARATOR_SVG_LOC}></use>
          </svg>
          <a target="_blank" href=${s.link}>
            <div class="item ${t===a.PLACE.UPPER?a.CSS_CLASS.ITEM_UPPER:a.CSS_CLASS.ITEM_LOWER}">${s.name}</div>
          </a>`),f=(e,t=!1)=>{let s=document.createElement("div"),r=document.createElement("div");return s.classList.add("items","marquee"),t&&s.classList.add("reverse"),r.classList.add("items","marquee"),t&&r.classList.add("reverse"),r.ariaHidden="true",s.innerHTML=e.join(""),r.innerHTML=e.join(""),l.insertAdjacentElement("beforeend",s),l.insertAdjacentElement("beforeend",r),{element1:s,element2:r}},y=(e,t,s=a.POSITION.BEFORE_END)=>{const{element1:r,element2:n}=t;e.insertAdjacentElement(s,r),e.insertAdjacentElement(s,n)},k=f(S(E)),O=f(S(E,a.PLACE.LOWER),!0);y(l,k);y(C,O);document.addEventListener("DOMContentLoaded",()=>{new _("#questions-list",{duration:250,showMultiple:!1}).open(0)});document.addEventListener("DOMContentLoaded",()=>{const e=document.getElementById("contact-form"),t=document.getElementById("modal"),s=document.getElementById("modal-message"),r=document.querySelector(".close"),n=()=>{t.style.display="none"};r.addEventListener("click",n),window.addEventListener("click",o=>{o.target===t&&n()}),window.addEventListener("keydown",o=>{o.key==="Escape"&&n()}),e.addEventListener("submit",async o=>{o.preventDefault();const i=e.email.value,h=e.message.value;try{(await fetch("https://portfolio-js.b.goit.study/api-docs/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:i,message:h})})).ok?(s.innerHTML='<h3 class="modal-success">Thank you for your interest in cooperation!</h3><p class="modal-info">The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.</p>',e.reset()):s.textContent="There was an error with your request. Please try again.",t.style.display="block"}catch{s.textContent="An error occurred. Please try again.",t.style.display="block"}}),r.addEventListener("click",()=>{t.style.display="none"}),window.addEventListener("click",o=>{o.target===t&&(t.style.display="none")})});p.defaults.baseURL="https://portfolio-js.b.goit.study/api/";const u=document.querySelector(".btn-next"),m=document.querySelector(".btn-prev"),v=document.querySelector(".error-message");window.addEventListener("resize",d);document.addEventListener("keydown",e=>{e.key==="ArrowRight"?w():e.key==="ArrowLeft"&&g()});function w(){c.slideNext(),d()}function g(){c.slidePrev(),d()}function d(){c.isBeginning?m.classList.add("button-disabled"):m.classList.remove("button-disabled"),c.isEnd?u.classList.add("button-disabled"):u.classList.remove("button-disabled")}u.addEventListener("click",w);m.addEventListener("click",g);const c=new b(".swiper",{slidesPerView:1,spaceBetween:16,speed:800,breakpoints:{0:{slidesPerView:1},768:{slidesPerView:1},1280:{slidesPerView:2}}}),R=document.querySelector(".carousel-wrapper");async function T(){try{return(await p("/reviews")).data}catch{return v.classList.remove("hidden"),[]}}async function A(){const e=await T();if(e.length===0){v.classList.remove("hidden");return}const t=e.map(({review:s,author:r,avatar_url:n})=>`
      <div class="swiper-slide feedback-item">
        <p class="feedback-text">${s}</p>
        <div class="feedback-info">
          <img src="${n}" alt="${r}" class="feedback-avatar" />
          <span class="feedback-author">${r}</span>
        </div>
      </div>
    `).join("");R.insertAdjacentHTML("beforeend",t),c.update(),d()}A();
//# sourceMappingURL=index.js.map
